# Generated by Django 5.0.6 on 2024-05-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='example@example.com', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='stuname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
